logging:
  level:
    org.springframework: INFO
    com.apple.assignment.flagpicker: DEBUG

storage:
  type: mongo


spring:
  mongodb:
    host: localhost
    database: flagpicker
    port: 27017



cache:
  guava:
    flag:
      name: CountryFlagCache
      ttl: 60