server:
  port: 8080
  servlet:
    context-path: /flag-picker


logging:
  level:
    org.springframework: INFO
    com.apple.assignment.flagpicker: DEBUG



management:
  endpoints:
    web:
      exposure:
        include: prometheus